application: regal-sun-100211
version: 1
runtime: php55
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /
  script: helloworld.php
- url: /convert
  script: convert.php
- url: /show
  script: show.php
- url: /getword
  script: getword.php
- url: /madlib
  script: madlib.php
- url: /madlib2
  script: madlib2.php
- url: /test
  script: test.php